[
    {
        "Inventory__c": "a06Qy00000M1uDCIAZ",
        "Order_Status__c": "out for delivery",
        "Total_Price__c": "2000.0",
        "Order_Date__c": "2025-11-25",
        "warehouse_city__c": "Bangalore",
        "type": "order__c",
        "DeliveryPartner__c": "a05Qy00001CfL13IAF",
        "Customer__c": "a04Qy00000CiynzIAB",
        "Quantity__c": "2.0",
        "Invoice__c": null,
        "Order_Id__c": "ORD101",
        "Delivery_Address__c": "KPHB, Hyderabad",
        "Id": "a08Qy00000TqcmsIAB",
        "IsCancelled__c": "false",
        "Delivery_Date__c": "2025-11-29",
        "Transit__c": "a09Qy00000FEekvIAD"
    },
    {
        "Inventory__c": null,
        "Order_Status__c": "shipped",
        "Total_Price__c": "1000.0",
        "Order_Date__c": null,
        "warehouse_city__c": "Bangalore",
        "type": "order__c",
        "DeliveryPartner__c": "a05Qy0000186RMzIAM",
        "Customer__c": "a04Qy00000CiynzIAB",
        "Quantity__c": "2.0",
        "Invoice__c": null,
        "Order_Id__c": "ORD1002",
        "Delivery_Address__c": "12 MG Road, Bangalore, Karnataka",
        "Id": "a08Qy00000TqoknIAB",
        "IsCancelled__c": "false",
        "Delivery_Date__c": "2025-12-22",
        "Transit__c": null
    },
    {
        "Inventory__c": "a06Qy00000LOzr4IAD",
        "Order_Status__c": "out for delivery",
        "Total_Price__c": "110000.0",
        "Order_Date__c": "2025-11-21",
        "warehouse_city__c": "banglore",
        "type": "order__c",
        "DeliveryPartner__c": "a05Qy00001DiOmQIAV",
        "Customer__c": "a04Qy00000EpVg4IAF",
        "Quantity__c": "2.0",
        "Invoice__c": null,
        "Order_Id__c": "ORD1003",
        "Delivery_Address__c": "Kukatpaly, Hyderabad",
        "Id": "a08Qy00000UkLRZIA3",
        "IsCancelled__c": "false",
        "Delivery_Date__c": "2025-11-30",
        "Transit__c": "a09Qy00000F8E1hIAF"
    },
    {
        "Inventory__c": "a06Qy00000LOzr4IAD",
        "Order_Status__c": "shipped",
        "Total_Price__c": "110000.0",
        "Order_Date__c": "2025-11-21",
        "warehouse_city__c": "Hyderabad",
        "type": "order__c",
        "DeliveryPartner__c": "a05Qy00001CfL13IAF",
        "Customer__c": "a04Qy00000EpVg4IAF",
        "Quantity__c": "2.0",
        "Invoice__c": "a07Qy00000mzfXUIAY",
        "Order_Id__c": "ORD1004",
        "Delivery_Address__c": "Gachibowi, Hyderabad",
        "Id": "a08Qy00000Un1L3IAJ",
        "IsCancelled__c": "false",
        "Delivery_Date__c": "2025-11-29",
        "Transit__c": "a09Qy00000FCbpeIAD"
    },
    {
        "Inventory__c": "a06Qy00000LOzr4IAD",
        "Order_Status__c": "shipped",
        "Total_Price__c": "345.0",
        "Order_Date__c": "2025-11-21",
        "warehouse_city__c": "chennai",
        "type": "order__c",
        "DeliveryPartner__c": "a05Qy00001CfL13IAF",
        "Customer__c": "a04Qy00000CiynzIAB",
        "Quantity__c": "2.0",
        "Invoice__c": null,
        "Order_Id__c": "ORD1005",
        "Delivery_Address__c": "Road, chennai, tamilnadu",
        "Id": "a08Qy00000Uw0eHIAR",
        "IsCancelled__c": "false",
        "Delivery_Date__c": "2025-12-22",
        "Transit__c": null
    },
    {
        "Inventory__c": "a06Qy00000M8zJfIAJ",
        "Order_Status__c": "Placed",
        "Total_Price__c": "2000.0",
        "Order_Date__c": "2025-11-25",
        "warehouse_city__c": "Bangalore",
        "type": "order__c",
        "DeliveryPartner__c": "a05Qy00001CfL13IAF",
        "Customer__c": "a04Qy00000D9T6cIAF",
        "Quantity__c": "1.0",
        "Invoice__c": null,
        "Order_Id__c": "ORD1006",
        "Delivery_Address__c": "Kukatpally, Hyderabad",
        "Id": "a08Qy00000Uz537IAB",
        "IsCancelled__c": "false",
        "Delivery_Date__c": "2025-11-30",
        "Transit__c": null
    },
    {
        "Inventory__c": "a06Qy00000M1uDCIAZ",
        "Order_Status__c": "Placed",
        "Total_Price__c": "2000.0",
        "Order_Date__c": "2025-11-25",
        "warehouse_city__c": "Bangalore",
        "type": "order__c",
        "DeliveryPartner__c": "a05Qy00001DiOmQIAV",
        "Customer__c": "a04Qy00000D9T6cIAF",
        "Quantity__c": "1.0",
        "Invoice__c": null,
        "Order_Id__c": "ORD1007",
        "Delivery_Address__c": "KPB, Hyderabad",
        "Id": "a08Qy00000V2NzZIAV",
        "IsCancelled__c": "false",
        "Delivery_Date__c": "2025-11-29",
        "Transit__c": null
    },
    {
        "Inventory__c": "a06Qy00000M1uDCIAZ",
        "Order_Status__c": "shipped",
        "Total_Price__c": "2000.0",
        "Order_Date__c": "2025-11-28",
        "warehouse_city__c": "Bangalore",
        "type": "order__c",
        "DeliveryPartner__c": null,
        "Customer__c": "a04Qy00000D9T6cIAF",
        "Quantity__c": "1.0",
        "Invoice__c": null,
        "Order_Id__c": "ORD1008",
        "Delivery_Address__c": "KPHB, Hyderabad",
        "Id": "a08Qy00000VAxTBIA1",
        "IsCancelled__c": "false",
        "Delivery_Date__c": "2025-12-12",
        "Transit__c": null
    },
    {
        "Inventory__c": "a06Qy00000LOzr4IAD",
        "Order_Status__c": "packaged",
        "Total_Price__c": "450.0",
        "Order_Date__c": "2025-11-29",
        "warehouse_city__c": "Bangalore",
        "type": "order__c",
        "DeliveryPartner__c": null,
        "Customer__c": "a04Qy00000CiynzIAB",
        "Quantity__c": "1.0",
        "Invoice__c": null,
        "Order_Id__c": "ORD1009",
        "Delivery_Address__c": "LB Nagar, Hyderabad",
        "Id": "a08Qy00000VBlGIIA1",
        "IsCancelled__c": "false",
        "Delivery_Date__c": null,
        "Transit__c": null
    }
]