[
    {
        "inventory": "a06Qy00000M1uDCIAZ",
        "orderStatus": "out for delivery",
        "totalPrice": "2000.0",
        "orderDate": "2025-11-25",
        "deliveryPartner": "a05Qy00001CfL13IAF",
        "customer": "a04Qy00000CiynzIAB",
        "quantity": "2.0",
        "invoice": null,
        "orderId": "ORD101",
        "deliveryAddress": "KPHB, Hyderabad",
        "warehouseCity": null
    },
    {
        "inventory": null,
        "orderStatus": "shipped",
        "totalPrice": "1000.0",
        "orderDate": null,
        "deliveryPartner": "a05Qy0000186RMzIAM",
        "customer": "a04Qy00000CiynzIAB",
        "quantity": "2.0",
        "invoice": null,
        "orderId": "ORD1002",
        "deliveryAddress": "12 MG Road, Bangalore, Karnataka",
        "warehouseCity": null
    },
    {
        "inventory": "a06Qy00000LOzr4IAD",
        "orderStatus": "out for delivery",
        "totalPrice": "110000.0",
        "orderDate": "2025-11-21",
        "deliveryPartner": "a05Qy00001DiOmQIAV",
        "customer": "a04Qy00000EpVg4IAF",
        "quantity": "2.0",
        "invoice": null,
        "orderId": "ORD1003",
        "deliveryAddress": "Kukatpaly, Hyderabad",
        "warehouseCity": null
    },
    {
        "inventory": "a06Qy00000LOzr4IAD",
        "orderStatus": "shipped",
        "totalPrice": "110000.0",
        "orderDate": "2025-11-21",
        "deliveryPartner": "a05Qy00001CfL13IAF",
        "customer": "a04Qy00000EpVg4IAF",
        "quantity": "2.0",
        "invoice": "a07Qy00000mzfXUIAY",
        "orderId": "ORD1004",
        "deliveryAddress": "Gachibowi, Hyderabad",
        "warehouseCity": null
    },
    {
        "inventory": "a06Qy00000LOzr4IAD",
        "orderStatus": "shipped",
        "totalPrice": "345.0",
        "orderDate": "2025-11-21",
        "deliveryPartner": "a05Qy00001CfL13IAF",
        "customer": "a04Qy00000CiynzIAB",
        "quantity": "2.0",
        "invoice": null,
        "orderId": "ORD1005",
        "deliveryAddress": "Road, chennai, tamilnadu",
        "warehouseCity": null
    },
    {
        "inventory": "a06Qy00000M8zJfIAJ",
        "orderStatus": "Placed",
        "totalPrice": "2000.0",
        "orderDate": "2025-11-25",
        "deliveryPartner": "a05Qy00001CfL13IAF",
        "customer": "a04Qy00000D9T6cIAF",
        "quantity": "1.0",
        "invoice": null,
        "orderId": "ORD1006",
        "deliveryAddress": "Kukatpally, Hyderabad",
        "warehouseCity": null
    },
    {
        "inventory": "a06Qy00000M1uDCIAZ",
        "orderStatus": "Placed",
        "totalPrice": "2000.0",
        "orderDate": "2025-11-25",
        "deliveryPartner": "a05Qy00001DiOmQIAV",
        "customer": "a04Qy00000D9T6cIAF",
        "quantity": "1.0",
        "invoice": null,
        "orderId": "ORD1007",
        "deliveryAddress": "KPB, Hyderabad",
        "warehouseCity": null
    },
    {
        "inventory": "a06Qy00000M1uDCIAZ",
        "orderStatus": "shipped",
        "totalPrice": "2000.0",
        "orderDate": "2025-11-28",
        "deliveryPartner": null,
        "customer": "a04Qy00000D9T6cIAF",
        "quantity": "1.0",
        "invoice": null,
        "orderId": "ORD1008",
        "deliveryAddress": "KPHB, Hyderabad",
        "warehouseCity": null
    },
    {
        "inventory": "a06Qy00000LOzr4IAD",
        "orderStatus": "packaged",
        "totalPrice": "450.0",
        "orderDate": "2025-11-29",
        "deliveryPartner": null,
        "customer": "a04Qy00000CiynzIAB",
        "quantity": "1.0",
        "invoice": null,
        "orderId": "ORD1009",
        "deliveryAddress": "LB Nagar, Hyderabad",
        "warehouseCity": null
    }
]